### ISSUE TITLE
Some UI tests failing in Maven build

### ISSUE THREAD

**Issue by thomas-fritsch** [thomas-fritsch/psdt#5]
Some UI tests (all test cases in AutoEditTest, OutlineTreeProviderTest, EditorActionTest) are faiing in Maven/Tycho build.  
For example: 

```
java.lang.AssertionError: Opened Editor with id:de.tfritsch.psdt.Postscript, is not an XtextEditor
    at org.junit.Assert.fail(Assert.java:88)
    at org.eclipse.xtext.junit4.ui.AbstractEditorTest.openEditor(AbstractEditorTest.java:48)
    at org.eclipse.xtext.junit4.ui.AbstractAutoEditTest.openEditor(AbstractAutoEditTest.java:57)
    at de.tfritsch.psdt.tests.AutoEditTest.testAngleBrackets(AutoEditTest.java:54)
```

However, these tests run fine when started from Eclipse IDE (Run as -> JUnit Plug-in Test).

**Comment by thomas-fritsch** [comment]
Temporary work-around:  
Disabled these 3 test-classes in  `de.tfritsch.psdt.tests/pom.xml`
