### ISSUE TITLE
Perspective UI test failing in Maven build

### ISSUE THREAD

**Issue by thomas-fritsch** [thomas-fritsch/psdt#7]
UI test case PerspectiveTest is failing in Maven/Tycho build.

```
org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
    at org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:4061)
    at org.eclipse.ui.internal.WorkbenchWindow.setup(WorkbenchWindow.java:733)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:888)
    at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:120)
    at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:85)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.inject(ContextInjectionFactory.java:73)
    at org.eclipse.ui.internal.Workbench.createWorkbenchWindow(Workbench.java:1480)
    at org.eclipse.ui.internal.Workbench.getActiveWorkbenchWindow(Workbench.java:1453)
    at de.tfritsch.psdt.tests.PerspectiveTest.testPostscriptPerspective(PerspectiveTest.java:41)
```

However, this test runs fine when started from Eclipse IDE (Run as -> JUnit Plug-in Test).

**Comment by thomas-fritsch** [comment]
Temporary work-around:

Disabled this test-class in `de.tfritsch.psdt.tests/pom.xml`

**Comment by thomas-fritsch** [comment]
Same exception also occuring with new [WizardTest](https://github.com/thomas-fritsch/psdt/commit/8598a1b1e812d171708ca6104bd59e1fafe9e2fb)
